# .achecker.yml

ruleArchive: latest

policies:
  - IBM_Accessibility

failLevels:
  - violation

reportLevels:
  - violation

outputFormat:
  - json

outputFolder: results

outputFilenameTimestamp: true

puppeteerArgs:
  - --no-sandbox
  - --disable-setuid-sandbox
