# .achecker.yml

ruleArchive: latest

policies:
  - IBM_Accessibility

failLevels:
  - violation
  - potentialviolation

reportLevels:
  - violation
  - potentialviolation
  - recommendation
  - potentialrecommendation
  - manual

outputFormat:
  - json

outputFolder: results

outputFilenameTimestamp: true

puppeteerArgs:
  - --no-sandbox
  - --disable-setuid-sandbox
